### ISSUE TITLE
En la vista mobile, añadir margin en los contenedores del footer.

### ISSUE THREAD

**Issue by DaniloBurbano** [JuanCruzSiryi/mercadoliebre-jcsiryi#1]
<img width="221" alt="image" src="https://user-images.githubusercontent.com/62822577/214460502-10bcda13-d533-45f1-8ca7-ac0257f07523.png">

**Comment by JuanCruzSiryi** [comment]
**Fixed.**

Danilo, thanks for the observation.

See u again.
