### ISSUE TITLE
Excelente trabajo Juan Cruz!

### ISSUE THREAD

**Issue by liliandevico** [JuanCruzSiryi/mercadoliebre-jcsiryi#3]
Están todos los elementos requeridos, el contenido de los artículos esta centrado, el sitio se adapta a todas la resoluciones de pantalla, cuenta con u formulario de registro de usuarios y de login, al clickear enviar re direccionan al home. Se puede navegar entre todas sus vistas. Se utilizaron animaciones de CSS. El header esta balanceado, quizás el logo podría ser un poquito mas grande, pero en su version actual el header esta excelente. Me gusto la tipología de letra que uso.

**Comment by JuanCruzSiryi** [comment]
Muchísimas gracias Lilian por la devolución. Me comprometo a seguir por este camino.
Un saludo.
